import '../css/tokens.css';
import '../css/base.css';
import '../css/components.css';
import '../css/sections.css';

import { init as initLoader }          from './modules/loader.js';
import { init as initCursor }          from './modules/cursor.js';
import { init as initPseudoBg }        from './modules/pseudo-bg.js';
import { init as initEntryRupture }    from './modules/entry-rupture.js';
import { init as initNavigation }      from './modules/navigation.js';
import { init as initYouAreHere }      from './modules/you-are-here.js';
import { init as initNavigationGuard } from './modules/navigation-guard.js';
import { init as initMinimap }         from './modules/minimap.js';
import { init as initReveal }          from './modules/reveal.js';
import { init as initCharMatrix }      from './modules/char-matrix.js';
import { init as initSquareWord }      from './modules/square-word.js';
import { init as initGlyphQuiz }       from './modules/glyph-quiz.js';
import { init as initTheoryReveal }    from './modules/theory-reveal.js';
import { init as initArGrid }          from './modules/ar-grid.js';

initLoader();
initCursor();
initPseudoBg();
initEntryRupture();
initNavigation();
initYouAreHere();
initNavigationGuard();
initMinimap();
initReveal();
initCharMatrix();
initSquareWord();
initGlyphQuiz();
initTheoryReveal();
initArGrid();